# Generated by Django 2.0.2 on 2018-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('cordenates', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('temperature', models.CharField(max_length=8)),
                ('searched_at', models.DateTimeField(auto_now=True)),
                ('unit_of_measurement', models.CharField(max_length=32)),
            ],
        ),
    ]
